/* AUTO-GENERATED by scripts/extract-gamification-seed.cjs — do not edit by hand */
/* Source: frontend/src/data/mockData.ts */

exports.challenges = [
  {
    id: '1',
    title: 'Password Security Basics',
    description: 'Learn the fundamentals of creating and managing secure passwords.',
    type: 'password',
    xpReward: 100,
    reputationReward: 5,
    duration: 3,
    difficulty: 'beginner',
    category: 'password',
    steps: [
      {
        id: '1-1',
        type: 'information',
        content: {
          title: 'Password Best Practices',
          description: 'A password is like a toothbrush; you should not share it and renew it every 6 months.',
          image: 'https://images.pexels.com/photos/60504/security-protection-anti-virus-software-60504.jpeg'
        }
      },
      {
        id: '1-2',
        type: 'password-create',
        content: {
          minLength: 12,
          requireCapital: true,
          requireNumber: true,
          requireSpecial: true
        }
      },
      {
        id: '1-3',
        type: 'question',
        content: {
          question: 'Which of the following are significant cybersecurity threats or risks?',
          options: [
            { id: '1', text: 'Phishing attacks', isCorrect: true },
            { id: '2', text: 'Poor password management', isCorrect: true },
            { id: '3', text: 'Regular software updates', isCorrect: false },
            { id: '4', text: 'Using password managers', isCorrect: false }
          ],
          multipleAnswers: true
        },
        explanation: 'Phishing attacks and poor password management are major security risks that can compromise both personal and organizational security. Regular updates and password managers actually help improve security.'
      }
    ]
  },
  {
    id: '2',
    title: 'Phishing Awareness',
    description: 'Learn to identify and avoid phishing attempts in emails and messages.',
    type: 'scenario',
    xpReward: 150,
    reputationReward: 8,
    duration: 5,
    difficulty: 'beginner',
    category: 'phishing',
    steps: [
      {
        id: '2-1',
        type: 'information',
        content: {
          title: 'Understanding Phishing',
          description: 'Phishing attacks are deceptive attempts to steal sensitive information by posing as trustworthy entities.',
          image: 'https://images.pexels.com/photos/5935794/pexels-photo-5935794.jpeg'
        }
      },
      {
        id: '2-2',
        type: 'scenario',
        content: {
          situation: 'You receive an urgent email from your "bank" asking you to verify your account by clicking a link. The email address is support@bank-secure-verify.com. What should you do?',
          options: [
            {
              id: '1',
              text: 'Click the link to verify your account',
              isCorrect: false,
              consequence: 'This could lead to your banking credentials being stolen!'
            },
            {
              id: '2',
              text: 'Contact your bank directly using their official phone number',
              isCorrect: true,
              consequence: 'Good choice! Always verify suspicious requests through official channels.'
            }
          ]
        }
      }
    ]
  },
  {
    id: '3',
    title: 'Incident Response Steps',
    description: 'Learn the correct sequence of steps to take during a security incident.',
    type: 'sequential',
    xpReward: 200,
    reputationReward: 10,
    duration: 7,
    difficulty: 'intermediate',
    category: 'incident-response',
    steps: [
      {
        id: '3-1',
        type: 'information',
        content: {
          title: 'Incident Response Framework',
          description: 'Security incidents require a structured approach. The following challenge will test your knowledge of proper incident response procedures.',
          image: 'https://images.pexels.com/photos/4050315/pexels-photo-4050315.jpeg'
        }
      },
      {
        id: '3-2',
        type: 'sequential',
        content: {
          question: 'Arrange these incident response steps in the correct order:',
          steps: [
            { 
              id: 's1', 
              text: 'Identify and contain the threat', 
              correctPosition: 1 
            },
            { 
              id: 's2', 
              text: 'Collect and preserve evidence', 
              correctPosition: 2 
            },
            { 
              id: 's3', 
              text: 'Analyze the breach and determine impact', 
              correctPosition: 3 
            },
            { 
              id: 's4', 
              text: 'Remove the threat and recover systems', 
              correctPosition: 4 
            },
            { 
              id: 's5', 
              text: 'Document lessons learned and update response plan', 
              correctPosition: 5 
            }
          ]
        },
        explanation: 'The proper sequence for incident response begins with identification and containment to stop further damage, followed by evidence collection before the scene changes. Analysis comes next to understand the scope, followed by removal and recovery. Finally, documentation of lessons learned helps improve future responses.'
      }
    ]
  },
  {
    id: '4',
    title: 'Spotting Phishing Attempts',
    description: 'Learn to identify genuine vs. fake login screens and emails.',
    type: 'verification',
    xpReward: 175,
    reputationReward: 12,
    duration: 6,
    difficulty: 'beginner',
    category: 'phishing',
    steps: [
      {
        id: '4-1',
        type: 'information',
        content: {
          title: 'Visual Phishing Indicators',
          description: 'Phishers create convincing copies of legitimate websites and emails. In this challenge, you\'ll learn to spot the differences between real and fake examples.',
          image: 'https://images.pexels.com/photos/60504/security-protection-anti-virus-software-60504.jpeg'
        }
      },
      {
        id: '4-2',
        type: 'image-verification',
        content: {
          question: 'Identify which of the following emails are legitimate and which are phishing attempts:',
          images: [
            {
              id: 'img1',
              imageUrl: 'https://images.pexels.com/photos/6963944/pexels-photo-6963944.jpeg',
              caption: 'DocuSign document review request',
              isReal: false,
              explanation: 'This is a phishing attempt. Notice the suspicious sender email (review@docusign-review.com) and generic greeting.'
            },
            {
              id: 'img2',
              imageUrl: 'https://images.pexels.com/photos/5935794/pexels-photo-5935794.jpeg',
              caption: 'Password reset from your bank',
              isReal: false,
              explanation: 'This is fake. The URL in the email points to a suspicious domain, not your bank\'s official website.'
            },
            {
              id: 'img3',
              imageUrl: 'https://images.pexels.com/photos/5935794/pexels-photo-5935794.jpeg',
              caption: 'Order confirmation from a known retailer',
              isReal: true,
              explanation: 'This is legitimate. The email contains your order number, uses your name, and the sender domain matches the retailer.'
            },
            {
              id: 'img4',
              imageUrl: 'https://images.pexels.com/photos/5935794/pexels-photo-5935794.jpeg',
              caption: 'Calendar invitation from a colleague',
              isReal: true,
              explanation: 'This is legitimate. The email comes from your organization\'s domain and contains specific meeting details.'
            }
          ],
          multipleAnswers: true
        },
        explanation: 'Always check for secure connections (HTTPS), correct domain names, proper spelling, and valid certificates when verifying a website\'s legitimacy.'
      }
    ]
  },
  {
    id: '5',
    title: 'Inbox phishing drill',
    description: 'Review a simulated mailbox and classify each message as phishing or legitimate.',
    type: 'simulation',
    xpReward: 120,
    reputationReward: 10,
    duration: 8,
    difficulty: 'intermediate',
    category: 'phishing',
    steps: [
      {
        id: '5-1',
        type: 'phishing-inbox',
        content: {
          instructions:
            'For each message, choose Report phishing or Legitimate. Classify every email before you submit.',
          emails: [
            {
              id: 'e1',
              from: 'IT Support <itsupport@company-internal.example>',
              subject: 'Password expires today',
              preview: 'Your password will expire…',
              body:
                'Dear employee,\n\nYour password expires in 24 hours. Click here to verify: http://evil-login.example.com\n\nThanks,\nIT',
              isPhishing: true,
            },
            {
              id: 'e2',
              from: 'hr@company.com',
              subject: 'Benefits enrollment window',
              preview: 'Open enrollment runs through Friday…',
              body:
                'Hello,\n\nOpen enrollment closes this Friday. Use the HR portal from the intranet home page—do not use links in email to log in.\n\n— HR',
              isPhishing: false,
            },
          ],
        },
        explanation:
          'Phishing often uses urgency and credential links to unknown hosts. Trusted internal notices rarely ask you to authenticate via an email link.',
      },
    ],
  },
  {
    id: '6',
    title: 'Compliance micro-course',
    description: 'Video refresher, acceptable-use policy attestation, and a quick check.',
    type: 'quiz',
    xpReward: 90,
    reputationReward: 8,
    duration: 12,
    difficulty: 'beginner',
    category: 'general',
    steps: [
      {
        id: '6-1',
        type: 'video-check',
        content: {
          title: 'Why reporting matters',
          videoUrl:
            'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',
          question: 'What is the best first step when you receive a suspicious email at work?',
          options: [
            { id: '6-1a', text: 'Forward it to friends to get their opinion', isCorrect: false },
            { id: '6-1b', text: 'Use the official report-phish button or follow your IT process', isCorrect: true },
            { id: '6-1c', text: 'Click all links to see where they go', isCorrect: false },
          ],
          multipleAnswers: false,
        },
        explanation: 'Always use your organization’s official reporting channel so security can analyze the message safely.',
      },
      {
        id: '6-2',
        type: 'policy-attestation',
        content: {
          policyId: 'practikal-aup-1',
          documentTitle: 'Acceptable use of company systems',
          documentBody:
            '1. Company systems are for business use and limited reasonable personal use.\n\n' +
            '2. You must not install unauthorized software or disable security controls.\n\n' +
            '3. Confidential data must be stored and shared only through approved tools.\n\n' +
            '4. Phishing and social-engineering attempts must be reported without engaging the sender.\n\n' +
            '5. Violations may result in disciplinary action up to and including termination.\n\n' +
            'By proceeding you confirm you have access to the full policy on your intranet.',
        },
        explanation: 'Attestation is recorded for compliance. Contact HR or IT if you cannot agree to these terms.',
      },
    ],
  },
];

exports.achievements = [
  {
    id: '1',
    title: 'Security Novice',
    description: 'Complete your first challenge',
    icon: 'award',
    progress: 0,
    total: 1
  },
  {
    id: '2',
    title: 'Streak Master',
    description: 'Maintain a 7-day challenge streak',
    icon: 'flame',
    progress: 0,
    total: 7
  },
  {
    id: '3',
    title: 'Password Pro',
    description: 'Complete all password security challenges',
    icon: 'key',
    progress: 0,
    total: 3
  }
];
